# Introduction

<center><img src="https://i.imgur.com/9hLRsjZ.jpg" height=400></center>

This dataset was scraped from [nextspaceflight.com](https://nextspaceflight.com/launches/past/?page=1) and includes all the space missions since the beginning of Space Race between the USA and the Soviet Union in 1957!

### Install Package with Country Codes

In [2]:
%pip install iso3166

Collecting iso3166
  Downloading iso3166-3.0.0-py3-none-any.whl.metadata (3.5 kB)
Downloading iso3166-3.0.0-py3-none-any.whl (8.9 kB)
Installing collected packages: iso3166
Successfully installed iso3166-3.0.0

### Upgrade Plotly

Run the cell below if you are working with Google Colab.

In [3]:
%pip install --upgrade plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (5.24.1)
Collecting plotly
  Downloading plotly-7.0.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from plotly) (2.25.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)
Downloading plotly-7.0.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 37.2 MB/s eta 0:00:00
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1
Successfully installed plotly-7.0.0

### Import Statements

In [4]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# These might be helpful:
from iso3166 import countries
from datetime import datetime, timedelta

### Notebook Presentation

In [5]:
pd.options.display.float_format = '{:,.2f}'.format

### Load the Data

In [6]:
df_data = pd.read_csv('mission_launches.csv')

# Preliminary Data Exploration

* What is the shape of `df_data`?
* How many rows and columns does it have?
* What are the column names?
* Are there any NaN values or duplicates?

In [ ]:
df_data.shape

(4324, 9)

In [ ]:
df_data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Organisation', 'Location', 'Date',
       'Detail', 'Rocket_Status', 'Price', 'Mission_Status'],
      dtype='object')

## Data Cleaning - Check for Missing Values and Duplicates

Consider removing columns containing junk data.

In [ ]:
df_data.isna().sum()

Unnamed: 0.1         0
Unnamed: 0           0
Organisation         0
Location             0
Date                 0
Detail               0
Rocket_Status        0
Price             3360
Mission_Status       0
dtype: int64

In [ ]:
df_data.duplicated().sum()

np.int64(0)

## Descriptive Statistics

In [ ]:
df_data.describe()

       Unnamed: 0.1  Unnamed: 0
count      4,324.00    4,324.00
mean       2,161.50    2,161.50
std        1,248.38    1,248.38
min            0.00        0.00
25%        1,080.75    1,080.75
50%        2,161.50    2,161.50
75%        3,242.25    3,242.25
max        4,323.00    4,323.00

In [ ]:
df_data.describe(include='all')

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
count,"4,324.00","4,324.00",4324,4324,4324,4324,4324,964,4324
unique,NaN,NaN,56,137,4319,4278,2,56,4
top,NaN,NaN,RVSN USSR,"Site 31/6, Baikonur Cosmodrome, Kazakhstan","Tue Aug 28, 1990 09:05 UTC",Cosmos-3MRB (65MRB) | BOR-5 Shuttle,StatusRetired,450.0,Success
freq,NaN,NaN,1777,235,2,6,3534,136,3879
mean,"2,161.50","2,161.50",NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,"1,248.38","1,248.38",NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,"1,080.75","1,080.75",NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,"2,161.50","2,161.50",NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,"3,242.25","3,242.25",NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,"4,323.00","4,323.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Number of Launches per Company

Create a chart that shows the number of space mission launches by organisation.

In [ ]:
launches_by_company = df_data['Organisation'].value_counts()
launches_by_company

Organisation
RVSN USSR           1777
Arianespace          279
General Dynamics     251
CASC                 251
NASA                 203
VKS RF               201
US Air Force         161
ULA                  140
Boeing               136
Martin Marietta      114
SpaceX               100
MHI                   84
Northrop              83
Lockheed              79
ISRO                  76
Roscosmos             55
ILS                   46
Sea Launch            36
ISAS                  30
Kosmotras             22
US Navy               17
Rocket Lab            13
ISA                   13
Eurockot              13
ESA                   13
Blue Origin           12
IAI                   11
ExPace                10
ASI                    9
CNES                   8
AMBA                   8
JAXA                   7
Land Launch            7
MITT                   7
UT                     5
CASIC                  5
KCST                   5
Exos                   4
CECLES                 4
Arm??e de l'Air        4
SRC                    3
KARI                   3
AEB                    3
RAE                    2
Yuzhmash               2
OKB-586                2
Virgin Orbit           1
IRGC                   1
OneSpace               1
Landspace              1
i-Space                1
Sandia                 1
Starsem                1
Khrunichev             1
Douglas                1
EER                    1
Name: count, dtype: int64

In [ ]:
fig = px.bar(
    x=launches_by_company.values,
    y=launches_by_company.index,
    orientation='h',
    title='Number of Space Mission Launches by Organisation',
    labels={
        'x': 'Number of Launches',
        'y': 'Organisation'
    }
)

fig.show()


# Number of Active versus Retired Rockets

How many rockets are active compared to those that are decomissioned?

In [ ]:
rocket_status = df_data['Rocket_Status'].value_counts()
rocket_status

Rocket_Status
StatusRetired    3534
StatusActive      790
Name: count, dtype: int64

In [ ]:
fig = px.bar(
    x=rocket_status.index,
    y=rocket_status.values,
    title='Number of Active vs Retired Rockets',
    labels={
        'x': 'Rocket Status',
        'y': 'Number of Rockets'
    }
)

fig.show()

# Distribution of Mission
Status

How many missions were successful?
How many missions failed?

In [ ]:
mission_status = df_data['Mission_Status'].value_counts()

mission_status

Mission_Status
Success              3879
Failure               339
Partial Failure       102
Prelaunch Failure       4
Name: count, dtype: int64

In [ ]:
fig = px.bar(
    x=mission_status.index,
    y=mission_status.values,
    title='Distribution of Mission Status',
    labels={
        'x': 'Mission Status',
        'y': 'Number of Missions'
    }
)

fig.show()

# How Expensive are the Launches?

Create a histogram and visualise the distribution. The price column is given in USD millions (careful of missing values).

In [ ]:
launch_prices = df_data['Price'].dropna()
launch_prices

0        50.0
1       29.75
3        65.0
4       145.0
5       64.68
        ...
3855     59.0
3971    63.23
3993    63.23
4000    63.23
4020    63.23
Name: Price, Length: 964, dtype: object

In [ ]:
fig = px.histogram(
    launch_prices,
    x='Price',
    title='Distribution of Launch Prices',
    labels={
        'Price': 'Launch Price (USD millions)',
        'count': 'Number of Launches'
    }
)

fig.show()

# Use a Choropleth Map to Show the Number of Launches by Country

* Create a choropleth map using [the plotly documentation](https://plotly.com/python/choropleth-maps/)
* Experiment with [plotly's available colours](https://plotly.com/python/builtin-colorscales/). I quite like the sequential colour `matter` on this map.
* You'll need to extract a `country` feature as well as change the country names that no longer exist.

Wrangle the Country Names

You'll need to use a 3 letter country code for each country. You might have to change some country names.

* Russia is the Russian Federation
* New Mexico should be USA
* Yellow Sea refers to China
* Shahrud Missile Test Site should be Iran
* Pacific Missile Range Facility should be USA
* Barents Sea should be Russian Federation
* Gran Canaria should be USA


You can use the iso3166 package to convert the country names to Alpha3 format.

In [ ]:
# Extract the country from the Location column
df_data['Country'] = df_data['Location'].str.split(',').str[-1].str.strip()

# Fix locations that are not actual country names
country_replacements = {
    'Russia': 'Russian Federation',
    'New Mexico': 'USA',
    'Yellow Sea': 'China',
    'Shahrud Missile Test Site': 'Iran',
    'Pacific Missile Range Facility': 'USA',
    'Barents Sea': 'Russian Federation',
    'Gran Canaria': 'USA'
}

df_data['Country'] = df_data['Country'].replace(country_replacements)

df_data['Country'].value_counts()

Country
Russian Federation    1398
USA                   1351
Kazakhstan             701
France                 303
China                  269
Japan                  126
India                   76
Pacific Ocean           36
Iran                    14
New Zealand             13
Israel                  11
Kenya                    9
Australia                6
North Korea              5
Brazil                   3
South Korea              3
Name: count, dtype: int64

In [ ]:
# Convert country names to 3-letter Alpha-3 country codes
df_data['Country_Code'] = df_data['Country'].apply(
    lambda country: countries.get(country).alpha3 if country in countries else None
)

# Count launches by country
launches_by_country = df_data['Country_Code'].value_counts().reset_index()
launches_by_country.columns = ['Country_Code', 'Launches']

# Create the choropleth map
fig = px.choropleth(
    launches_by_country,
    locations='Country_Code',
    color='Launches',
    color_continuous_scale='matter',
    title='Number of Space Launches by Country',
    labels={'Launches': 'Number of Launches'}
)

fig.show()



# Use a Choropleth Map to Show the Number of Failures by Country

In [ ]:
# Select only failed missions
failed_missions = df_data[df_data['Mission_Status'] == 'Failure']

# Count failures by country
failures_by_country = (
    failed_missions['Country_Code']
    .value_counts()
    .reset_index()
)

failures_by_country.columns = ['Country_Code', 'Failures']

failures_by_country

   Country_Code  Failures
0           USA       129
1           KAZ        72
2           RUS        63
3           CHN        19
4           FRA        13
5           JPN        10
6           IND         8
7           AUS         3
8           NZL         2
9           ISR         2
10          BRA         2

In [ ]:
fig = px.choropleth(
    failures_by_country,
    locations='Country_Code',
    color='Failures',
    color_continuous_scale='matter',
    title='Number of Failed Space Missions by Country',
    labels={'Failures': 'Number of Failures'}
)

fig.show()

# Create a Plotly Sunburst Chart of the countries, organisations, and mission status.

In [ ]:
sunburst_data = (
    df_data
    .groupby(['Country', 'Organisation', 'Mission_Status'])
    .size()
    .reset_index(name='Missions')
)

sunburst_data.head()

     Country Organisation Mission_Status  Missions
0  Australia         AMBA        Success         1
1  Australia       CECLES        Failure         2
2  Australia       CECLES        Success         1
3  Australia          RAE        Failure         1
4  Australia          RAE        Success         1

In [ ]:
fig = px.sunburst(
    sunburst_data,
    path=['Country', 'Organisation', 'Mission_Status'],
    values='Missions',
    title='Space Missions by Country, Organisation and Mission Status'

)

fig.show()

In [ ]:
fig.update_traces(
    textinfo='label+percent parent',
    hovertemplate='<b>%{label}</b><br>Missions: %{value}<extra></extra>'
)

fig.show()

# Analyse the Total Amount of Money Spent by Organisation on Space Missions

In [ ]:
# Convert Price to numeric values
df_data['Price'] = pd.to_numeric(df_data['Price'], errors='coerce')

# Calculate total money spent by each organisation
money_spent = (
    df_data.groupby('Organisation')['Price']
    .sum()
    .sort_values(ascending=False)
)

money_spent

Organisation
NASA               61,200.00
Arianespace        16,345.00
ULA                14,798.00
CASC                6,340.26
SpaceX              5,444.00
Northrop            3,930.00
MHI                 3,532.50
ISRO                2,177.00
US Air Force        1,550.92
VKS RF              1,548.90
ILS                 1,320.00
Boeing              1,241.00
Roscosmos           1,187.50
Martin Marietta       721.40
Kosmotras             638.00
Eurockot              543.40
Lockheed              280.00
JAXA                  168.00
Rocket Lab             97.50
ESA                    37.00
ExPace                 28.30
EER                    20.00
Sandia                 15.00
Virgin Orbit           12.00
ISAS                    0.00
ISA                     0.00
IRGC                    0.00
IAI                     0.00
Exos                    0.00
General Dynamics        0.00
CECLES                  0.00
CASIC                   0.00
CNES                    0.00
Douglas                 0.00
Blue Origin             0.00
AEB                     0.00
ASI                     0.00
AMBA                    0.00
Arm??e de l'Air         0.00
KARI                    0.00
RAE                     0.00
OneSpace                0.00
OKB-586                 0.00
MITT                    0.00
Khrunichev              0.00
KCST                    0.00
Land Launch             0.00
Landspace               0.00
Starsem                 0.00
Sea Launch              0.00
RVSN USSR               0.00
SRC                     0.00
UT                      0.00
US Navy                 0.00
Yuzhmash                0.00
i-Space                 0.00
Name: Price, dtype: float64

In [ ]:
fig = px.bar(
    x=money_spent.values,
    y=money_spent.index,
    orientation='h',
    title='Total Money Spent by Organisation on Space Missions',
    labels={
        'x': 'Total Cost (USD millions)',
        'y': 'Organisation'
    }
)

fig.show()

In [ ]:
fig.update_traces(
    text=money_spent.round(2),
    texttemplate='%{text}',
    textposition='outside'
)

fig.show()

# Analyse the Amount of Money Spent by Organisation per Launch

In [ ]:
# Calculate average money spent per launch by each organisation
money_per_launch = (
    df_data.groupby('Organisation')['Price']
    .mean()
    .dropna()
    .sort_values(ascending=False)
)

money_per_launch

Organisation
NASA              450.00
Boeing            177.29
Arianespace       170.26
ULA               151.00
ILS               101.54
MHI                95.47
Martin Marietta    80.16
US Air Force       59.65
JAXA               56.00
SpaceX             54.99
Roscosmos          51.63
Northrop           47.35
VKS RF             46.94
Eurockot           41.80
CASC               40.13
ESA                37.00
Lockheed           35.00
ISRO               32.49
Kosmotras          29.00
ExPace             28.30
EER                20.00
Sandia             15.00
Virgin Orbit       12.00
Rocket Lab          7.50
Name: Price, dtype: float64

In [ ]:
fig = px.bar(
    x=money_per_launch.values,
    y=money_per_launch.index,
    orientation='h',
    title='Average Money Spent per Launch by Organisation',
    labels={
        'x': 'Average Cost per Launch (USD millions)',
        'y': 'Organisation'
    }
)

fig.show()

In [ ]:
fig.update_traces(
    text=money_per_launch.round(2),
    texttemplate='%{text}',
    textposition='outside'
)

fig.show()

# Chart the Number of Launches per Year

In [15]:
# Extract the year from the Date column
launches_per_year = (
    df_data['Date']
    .apply(lambda x: x.year)
    .value_counts()
    .sort_index()
)

launches_per_year

Date
1957      3
1958     28
1959     20
1960     39
1961     52
       ...
2016     90
2017     92
2018    117
2019    109
2020     63
Name: count, Length: 64, dtype: int64

In [16]:
fig = px.line(
    x=launches_per_year.index,
    y=launches_per_year.values,
    markers=True,
    title='Number of Space Launches per year',
    labels={
        'x': 'Year',
        'y': 'Number of Launches'
    }
)

fig.show()

# Chart the Number of Launches Month-on-Month until the Present

Which month has seen the highest number of launches in all time? Superimpose a rolling average on the month on month time series chart.

In [17]:
#Count the number of launches for each month
launches_per_month = (
    df_data['Date']
    .apply(lambda x: x.strftime('%Y-%m'))
    .value_counts()
    .sort_index()
)

launches_per_month

Date
1957-10     1
1957-11     1
1957-12     1
1958-02     2
1958-03     3
           ..
2020-04     5
2020-05     9
2020-06     7
2020-07    14
2020-08     3
Name: count, Length: 747, dtype: int64

In [18]:
fig = px.line(
    x=launches_per_month.index,
    y=launches_per_month.values,
    markers=True,
    title='Number of Space Launches Month-on-Month',
    labels={
        'x': 'Month',
        'y': 'Number of Launches'
    }
)

fig.show()

# Launches per Month: Which months are most popular and least popular for launches?

Some months have better weather than others. Which time of year seems to be best for space missions?

In [19]:
# Calculate the total number of launches for each month
launches_by_month = (
    df_data['Date']
    .apply(lambda x: x.month)
    .value_counts()
    .sort_index()
)

# Give the months readable names
month_names = {
    1: 'January', 2: 'February', 3: 'March',
    4: 'April', 5: 'May', 6: 'June',
    7: 'July', 8: 'August', 9: 'September',
    10: 'October', 11: 'November', 12: 'December'
}

launches_by_month.index = launches_by_month.index.map(month_names)

launches_by_month

Date
January      268
February     336
March        353
April        383
May          326
June         402
July         351
August       373
September    365
October      381
November     336
December     450
Name: count, dtype: int64

In [20]:
fig = px.bar(
    x=launches_by_month.index,
    y=launches_by_month.values,
    title='Most and Least Popular Months for Space Launches',
    labels={
        'x': 'Month',
        'y': 'Number of Launches'
    },
    text=launches_by_month.values
)

fig.update_traces(textposition='outside')
fig.show()

# How has the Launch Price varied Over Time?

Create a line chart that shows the average price of rocket launches over time.

In [22]:
# Make sure Price contains numeric values
df_data['Price'] = pd.to_numeric(df_data['Price'], errors='coerce')

# Calculate the average launch price for each year
average_price_per_year = (
    df_data.groupby(
        df_data['Date'].apply(lambda x: x.year)
    )['Price']
    .mean()
    .dropna()
)

average_price_per_year

Date
1964    63.23
1965    63.23
1966    59.00
1967    59.00
1968    59.00
1969    59.00
1981   450.00
1982   345.20
1983   366.16
1984   380.13
1985   408.08
1986   310.27
1987    30.80
1988   241.45
1989   380.83
1990   289.15
1991   391.43
1992   319.35
1993   276.73
1994   221.51
1995   325.00
1996   243.20
1997   221.74
1998   152.12
1999   128.51
2000   173.12
2001   290.70
2002   185.59
2003    80.51
2004    92.74
2005    95.79
2006   138.61
2007   125.70
2008   129.75
2009   180.29
2010   148.40
2011   146.60
2012   122.29
2013    90.55
2014   102.55
2015    91.55
2016    79.46
2017    69.49
2018    64.75
2019    59.61
2020    56.65
Name: Price, dtype: float64

In [23]:
fig = px.line(
    x=average_price_per_year.index,
    y=average_price_per_year.values,
    markers=True,
    title='Average Launch Price Over Time',
    labels={
        'x': 'Year',
        'y': 'Average Launch Price (USD millions)'
    }
)

fig.show()

# Chart the Number of Launches over Time by the Top 10 Organisations.

How has the dominance of launches changed over time between the different players?

In [24]:
# Find the top 10 organisations by number of launches
top_10_organisations = (
    df_data['Organisation']
    .value_counts()
    .head(10)
    .index
)

top_10_organisations

Index(['RVSN USSR', 'Arianespace', 'General Dynamics', 'CASC', 'NASA',
       'VKS RF', 'US Air Force', 'ULA', 'Boeing', 'Martin Marietta'],
      dtype='object', name='Organisation')

In [25]:
# Filter the data to the top 10 organisations
top_10_data = df_data[
    df_data['Organisation'].isin(top_10_organisations)
].copy()

# Extract the year from each launch date
top_10_data['Year'] = top_10_data['Date'].apply(lambda x: x.year)

# Count launches by year and organisation
launches_top_10 = (
    top_10_data
    .groupby(['Year', 'Organisation'])
    .size()
    .reset_index(name='Launches')
)

launches_top_10

     Year      Organisation  Launches
0    1957         RVSN USSR         2
1    1958              NASA         2
2    1958         RVSN USSR         5
3    1958      US Air Force         2
4    1959  General Dynamics         1
..    ...               ...       ...
318  2019            VKS RF         8
319  2020       Arianespace         4
320  2020              CASC        19
321  2020               ULA         4
322  2020            VKS RF         3

[323 rows x 3 columns]

In [27]:
fig = px.line(
    launches_top_10,
    x='Year',
    y='Launches',
    color='Organisation',
    markers=True,
    title='Number of Space Launches Over Time by Top 10 Organisation',
    labels={
        'Year': 'Year',
        'Launches': 'Number of Launches',
        'Organisation': 'Organisation'
    }
)

fig.show()

# Cold War Space Race: USA vs USSR

The cold war lasted from the start of the dataset up until 1991.

In [28]:
# Filter the data for the Cold War Period (up to 1991)
cold_war_data = df_data[
    df_data['Date'].apply(lambda x: x.year) <= 1991
].copy()

# Group the launches by year and organisation
cold_war_launches = (
    cold_war_data
    .groupby([
        cold_war_data['Date'].apply(lambda x: x.year),
        'Organisation'
    ])
    .size()
    .reset_index(name='Launches')
)

cold_war_launches.head()

   Date Organisation  Launches
0  1957    RVSN USSR         2
1  1957      US Navy         1
2  1958         AMBA         7
3  1958         NASA         2
4  1958    RVSN USSR         5

In [29]:
fig = px.line(
    cold_war_launches,
    x='Date',
    y='Launches',
    color='Organisation',
    markers=True,
    title='Cold War Space Race: USA vs USSR',
    labels={
        'Date': 'Year',
        'Launches': 'Number of Launches',
        'Organisation': 'Organisation'
    }
)

fig.show()

## Create a Plotly Pie Chart comparing the total number of launches of the USSR and the USA

Hint: Remember to include former Soviet Republics like Kazakhstan when analysing the total number of launches.

In [31]:
# Extract the country from the launch location
country = df_data['Location'].str.split(',').str[-1].str.strip()

# Count USA launches
usa_launches = (country == 'USA').sum()

# Count USSR launches, including Kazakhstan
ussr_launches = country.isin([
    'Russia',
    'Kazakhstan'
]).sum()

cold_war_totals = pd.Series({
    'USSR': ussr_launches,
    'USA': usa_launches
})

cold_war_totals

USSR    2096
USA     1344
dtype: int64

In [32]:
fig = px.pie(
    values=cold_war_totals.values,
    names=cold_war_totals.index,
    title='Total Space Launches: USSR vs USA'
)

fig.show()

## Create a Chart that Shows the Total Number of Launches Year-On-Year by the Two Superpowers

In [33]:
# Count yearly launches for the USSR and USA
cold_war_data['Year'] = cold_war_data['Date'].apply(lambda x: x.year)

usa_yearly = (
    cold_war_data[cold_war_data['Location'].str.split(',').str[-1].str.strip() == 'USA']
    .groupby('Year')
    .size()
)

ussr_yearly = (
    cold_war_data[cold_war_data['Location'].str.split(',').str[-1].str.strip().isin(['Russia', 'Kazakhstan'])]
    .groupby('Year')
    .size()
)

yearly_superpower_launches = pd.DataFrame({
    'USA': usa_yearly,
    'USSR': ussr_yearly
}).fillna(0)

yearly_superpower_launches

      USA  USSR
Year
1957    1     2
1958   23     5
1959   16     4
1960   30     9
1961   43     9
1962   60    22
1963   17    24
1964   24    36
1965   33    53
1966   47    51
1967   26    75
1968   22    80
1969   17    83
1970   11    88
1971   16    93
1972   17    79
1973   17    84
1974   10    83
1975   15    89
1976   13    95
1977   14    97
1978   21    71
1979    9    36
1980   11    40
1981   13    51
1982   11    53
1983   13    46
1984   17    42
1985   16    51
1986    6    49
1987    6    42
1988    7    36
1989   16    26
1990   26    37
1991   18    29

In [34]:
fig = px.line(
    yearly_superpower_launches,
    x=yearly_superpower_launches.index,
    y=['USA', 'USSR'],
    markers=True,
    title='Year-on-Year Space Launches: USA vs USSR',
    labels={
        'x': 'Year',
        'value': 'Number of Launches',
        'variable': 'Superpower'
    }
)

fig.show()

## Chart the Total Number of Mission Failures Year on Year.

In [35]:
# Count mission failures for each year
failed_missions = df_data[
    df_data['Mission_Status'] == 'Failure'
].copy()

failed_missions['Year'] = failed_missions['Date'].apply(lambda x: x.year)

failures_by_year = (
    failed_missions
    .groupby('Year')
    .size()
)

failures_by_year

Year
1957     1
1958    20
1959     9
1960    20
1961    17
        ..
2016     2
2017     6
2018     2
2019     6
2020     6
Length: 64, dtype: int64

In [36]:
fig = px.line(
    x=failures_by_year.index,
    y=failures_by_year.values,
    markers=True,
    title='Total Number of Mission Failures Year on Year',
    labels={
        'x': 'Year',
        'y': 'Number of Mission Failures'
    }
)

fig.show()

## Chart the Percentage of Failures over Time

Did failures go up or down over time? Did the countries get better at minimising risk and improving their chances of success over time?

In [37]:
# Calculate total missions and failed missions for each year
yearly_total = (
    df_data['Date']
    .apply(lambda x: x.year)
    .value_counts()
    .sort_index()
)

yearly_failures = (
    df_data[df_data['Mission_Status'] == 'Failure']['Date']
    .apply(lambda x: x.year)
    .value_counts()
    .sort_index()
)

yearly_failure_percentage = (
    yearly_failures / yearly_total * 100
).fillna(0)

yearly_failure_percentage

Date
1957   33.33
1958   71.43
1959   45.00
1960   51.28
1961   32.69
        ...
2016    2.22
2017    6.52
2018    1.71
2019    5.50
2020    9.52
Name: count, Length: 64, dtype: float64

In [38]:
fig = px.line(
    x=yearly_failure_percentage.index,
    y=yearly_failure_percentage.values,
    markers=True,
    title='Percentage of Mission Failures Over Time',
    labels={
        'x': 'Year',
        'y': 'Failure Percentage (%)'
    }
)

fig.show()

In [39]:
fig = px.line(
    x=yearly_failure_percentage.index,
    y=yearly_failure_percentage.values,
    markers=True,
    title='Percentage of Mission Failures Over Time',
    labels={
        'x': 'Year',
        'y': 'Failure Percentage (%)'
    }
)

fig.update_yaxes(ticksuffix='%')
fig.show()

# For Every Year Show which Country was in the Lead in terms of Total Number of Launches up to and including including 2020)

Do the results change if we only look at the number of successful launches?

In [40]:
# Find the country with the most launches for each year up to 2020
yearly_country_launches = (
    df_data[df_data['Date'].apply(lambda x: x.year) <= 2020]
    .assign(
        Year=lambda x: x['Date'].apply(lambda d: d.year),
        Country=lambda x: x['Location'].str.split(',').str[-1].str.strip()
    )
    .groupby(['Year', 'Country'])
    .size()
    .reset_index(name='Launches')
)

country_leader_each_year = (
    yearly_country_launches
    .sort_values(['Year', 'Launches'], ascending=[True, False])
    .drop_duplicates('Year')
    .sort_values('Year')
)

country_leader_each_year

     Year     Country  Launches
0    1957  Kazakhstan         2
3    1958         USA        23
5    1959         USA        16
7    1960         USA        30
10   1961         USA        43
..    ...         ...       ...
396  2016         USA        27
405  2017         USA        30
406  2018       China        39
415  2019       China        33
426  2020       China        22

[64 rows x 3 columns]

In [41]:
# Find the country with the most successful launches for each year up to 2020
successful_launches = df_data[
    (df_data['Mission_Status'] == 'Success') &
    (df_data['Date'].apply(lambda x: x.year) <= 2020)
].copy()

successful_country_leader = (
    successful_launches
    .assign(
        Year=lambda x: x['Date'].apply(lambda d: d.year),
        Country=lambda x: x['Location'].str.split(',').str[-1].str.strip()
    )
    .groupby(['Year', 'Country'])
    .size()
    .reset_index(name='Successful Launches')
    .sort_values(['Year', 'Successful Launches'], ascending=[True, False])
    .drop_duplicates('Year')
    .sort_values('Year')
)

successful_country_leader

     Year     Country  Successful Launches
0    1957  Kazakhstan                    2
2    1958         USA                    5
4    1959         USA                    6
6    1960         USA                   16
8    1961         USA                   27
..    ...         ...                  ...
356  2016         USA                   26
363  2017         USA                   30
364  2018       China                   38
372  2019       China                   31
389  2020         USA                   20

[64 rows x 3 columns]

# Create a Year-on-Year Chart Showing the Organisation Doing the Most Number of Launches

Which organisation was dominant in the 1970s and 1980s? Which organisation was dominant in 2018, 2019 and 2020?

In [42]:
# Find the organisation with the most launches for each year
yearly_org_launches = (
    df_data[df_data['Date'].apply(lambda x: x.year) <= 2020]
    .assign(Year=lambda x: x['Date'].apply(lambda d: d.year))
    .groupby(['Year', 'Organisation'])
    .size()
    .reset_index(name='Launches')
)

organisation_leader_each_year = (
    yearly_org_launches
    .sort_values(['Year', 'Launches'], ascending=[True, False])
    .drop_duplicates('Year')
    .sort_values('Year')
)

organisation_leader_each_year

     Year  Organisation  Launches
0    1957     RVSN USSR         2
6    1958       US Navy        12
10   1959  US Air Force        10
15   1960  US Air Force        21
19   1961  US Air Force        23
..    ...           ...       ...
583  2016          CASC        22
611  2017        SpaceX        18
616  2018          CASC        37
632  2019          CASC        27
649  2020          CASC        19

[64 rows x 3 columns]

In [43]:
# Plot the organisation doing the most launches each year
fig = px.bar(
    organisation_leader_each_year,
    x='Year',
    y='Launches',
    color='Organisation',
    title='Year-on-Year Organisation with the Most Space Launches',
    labels={
        'Year': 'Year',
        'Launches': 'Number of Launches',
        'Organisation': 'Organisation'
    }
)

fig.show()

In [45]:
# Display the leading organisation and number of launches for each year
organisation_leader_each_year[['Year', 'Organisation', 'Launches']]

     Year  Organisation  Launches
0    1957     RVSN USSR         2
6    1958       US Navy        12
10   1959  US Air Force        10
15   1960  US Air Force        21
19   1961  US Air Force        23
..    ...           ...       ...
583  2016          CASC        22
611  2017        SpaceX        18
616  2018          CASC        37
632  2019          CASC        27
649  2020          CASC        19

[64 rows x 3 columns]